# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_type', models.CharField(choices=[('Address Type', 'Address Type'), ('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=30, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('City', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(max_length=20, null=True)),
                ('Zip', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20, null=True)),
                ('Mname', models.CharField(max_length=20, null=True)),
                ('Lname', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_type', models.CharField(choices=[('Date Type', 'Date Type'), ('birthdate', 'birthdate'), ('Other', 'Other')], max_length=30, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='MainModule.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_type', models.CharField(choices=[('Phone Type', 'Phone Type'), ('Home', 'Home'), ('Work', 'Work'), ('Cell', 'Cell'), ('Other', 'Other')], max_length=30, null=True)),
                ('Area_code', models.CharField(max_length=3, null=True)),
                ('Number', models.CharField(max_length=8, null=True)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='MainModule.Contacts')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='Contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='MainModule.Contacts'),
        ),
    ]
